dependencies {
  implementation(project(":com.io7m.exfilac.clock.api"))
  implementation(project(":com.io7m.exfilac.content_tree.api"))
  implementation(project(":com.io7m.exfilac.s3_uploader.api"))
  implementation(project(":com.io7m.exfilac.service.api"))

  implementation(libs.io7m.anethum.api)
  implementation(libs.io7m.blackthorne.core)
  implementation(libs.io7m.blackthorne.jxe)
  implementation(libs.io7m.darco.api)
  implementation(libs.io7m.darco.sqlite)
  implementation(libs.io7m.jaffirm.core)
  implementation(libs.io7m.jattribute.core)
  implementation(libs.io7m.jlexing.core)
  implementation(libs.io7m.jmulticlose.core)
  implementation(libs.io7m.junreachable.core)
  implementation(libs.io7m.jxe.core)
  implementation(libs.io7m.lanark.core)
  implementation(libs.io7m.seltzer.api)
  implementation(libs.io7m.taskrecorder.core)
  implementation(libs.io7m.trasco.api)
  implementation(libs.io7m.trasco.vanilla)
  implementation(libs.io7m.trasco.xml.schemas)

  implementation(libs.kotlin.stdlib)
  implementation(libs.logback.android)
  implementation(libs.opentelemetry.api)
  implementation(libs.opentelemetry.context)
  implementation(libs.slf4j)
  implementation(libs.xerces)
  implementation(libs.xerial.sqlite)
}
