[versions]
darco            = "2.0.0"
opentelemetry    = "1.41.0"
slf4j            = "2.0.16"
logback_android  = "3.0.0"
trasco           = "3.0.0"
anethum          = "1.1.1"
jlexing          = "3.2.0"
jxe              = "2.0.0"
junreachable     = "4.0.2"
blackthorne      = "2.0.2"
xerces           = "2.12.2"
junit            = "5.11.0"
junit_platform   = "1.11.0"
amazon_aws       = "2.27.8"
ervilla          = "1.0.0"
jade             = "1.0.3"

[libraries]
junit_jupiter_api       = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_jupiter_engine    = { module = "org.junit.jupiter:junit-jupiter-engine" , version.ref = "junit" }
junit_platform_commons  = { module = "org.junit.platform:junit-platform-commons" , version.ref = "junit_platform" }
junit_platform_engine   = { module = "org.junit.platform:junit-platform-engine" , version.ref = "junit_platform" }
junit_platform_launcher = { module = "org.junit.platform:junit-platform-launcher" , version.ref = "junit_platform" }
opentest4j              = { module = "org.opentest4j:opentest4j", version = "1.3.0" }
jqwik_api               = { module = "net.jqwik:jqwik-api", version = "1.9.0" }
jqwik_engine            = { module = "net.jqwik:jqwik-engine", version = "1.9.0" }

junit_obsolete = { module = "junit:junit", version = "4.13.2" }

kotlin_reflect              = { module = "org.jetbrains.kotlin:kotlin-reflect", version = "1.9.24" }
kotlin_stdlib               = { module = "org.jetbrains.kotlin:kotlin-stdlib", version = "2.0.20" }
kotlinx_coroutines          = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }
kotlinx_coroutines_android  = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.7.3" }
kotlinx_coroutines_core_jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version = "1.7.3" }

io7m_anethum_api         = { module = "com.io7m.anethum:com.io7m.anethum.api", version.ref = "anethum" }
io7m_blackthorne_core    = { module = "com.io7m.blackthorne:com.io7m.blackthorne.core", version.ref = "blackthorne" }
io7m_blackthorne_jxe     = { module = "com.io7m.blackthorne:com.io7m.blackthorne.jxe", version.ref = "blackthorne" }
io7m_darco_api           = { module = "com.io7m.darco:com.io7m.darco.api", version.ref = "darco" }
io7m_darco_sqlite        = { module = "com.io7m.darco:com.io7m.darco.sqlite", version.ref = "darco" }
io7m_ervilla_api         = { module = "com.io7m.ervilla:com.io7m.ervilla.api", version.ref = "ervilla" }
io7m_ervilla_ext         = { module = "com.io7m.ervilla:com.io7m.ervilla.test_extension", version.ref = "ervilla" }
io7m_ervilla_native_exec = { module = "com.io7m.ervilla:com.io7m.ervilla.native_exec", version.ref = "ervilla" }
io7m_jade_api            = { module = "com.io7m.jade:com.io7m.jade.api", version.ref = "jade" }
io7m_jade_spi            = { module = "com.io7m.jade:com.io7m.jade.spi", version.ref = "jade" }
io7m_jade_vanilla        = { module = "com.io7m.jade:com.io7m.jade.vanilla", version.ref = "jade" }
io7m_jaffirm_core        = { module = "com.io7m.jaffirm:com.io7m.jaffirm.core", version = "4.0.1" }
io7m_jattribute_core     = { module = "com.io7m.jattribute:com.io7m.jattribute.core", version = "1.0.1" }
io7m_jdeferthrow_core    = { module = "com.io7m.jdeferthrow:com.io7m.jdeferthrow.core", version = "1.3.0" }
io7m_jlexing_core        = { module = "com.io7m.jlexing:com.io7m.jlexing.core", version.ref = "jlexing" }
io7m_jmulticlose_core    = { module = "com.io7m.jmulticlose:com.io7m.jmulticlose.core", version = "1.1.3" }
io7m_junreachable_core   = { module = "com.io7m.junreachable:com.io7m.junreachable.core", version.ref = "junreachable" }
io7m_jxe_core            = { module = "com.io7m.jxe:com.io7m.jxe.core", version.ref = "jxe" }
io7m_lanark_core         = { module = "com.io7m.lanark:com.io7m.lanark.core", version = "1.2.0" }
io7m_peixoto_sdk         = { module = "com.io7m.peixoto:com.io7m.peixoto.sdk", version = "2.27.21" }
io7m_seltzer_api         = { module = "com.io7m.seltzer:com.io7m.seltzer.api", version = "1.1.0" }
io7m_taskrecorder_core   = { module = "com.io7m.taskrecorder:com.io7m.taskrecorder.core", version = "1.0.0" }
io7m_trasco_api          = { module = "com.io7m.trasco:com.io7m.trasco.api", version.ref = "trasco" }
io7m_trasco_vanilla      = { module = "com.io7m.trasco:com.io7m.trasco.vanilla", version.ref = "trasco" }
io7m_trasco_xml_schemas  = { module = "com.io7m.trasco:com.io7m.trasco.xml.schemas", version.ref = "trasco" }

xerial_sqlite           = { module = "org.xerial:sqlite-jdbc", version = "3.46.1.0" }
xerces                  = { module = "xerces:xercesImpl", version.ref = "xerces" }
stax_api                = { module = "javax.xml.stream:stax-api", version = "1.0-2" }
stax                    = { module = "stax:stax", version = "1.2.0" }

zxing_embedded = { module = "com.journeyapps:zxing-android-embedded", version = "4.3.0" }
zxing_core     = { module = "com.google.zxing:core", version = "3.4.1" }

slf4j           = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback_android = { module = "com.github.tony19:logback-android", version.ref = "logback_android" }
logback_core    = { module = "ch.qos.logback:logback-core", version = "1.4.8" }
logback_classic = { module = "ch.qos.logback:logback-classic", version = "1.4.8" }

opentelemetry_api       = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry_context   = { module = "io.opentelemetry:opentelemetry-context", version.ref = "opentelemetry" }

google_material = { module = "com.google.android.material:material", version = "1.12.0" }

apache_commons_io    = { module = "commons-io:commons-io", version = "2.16.1" }
apache_commons_lang3 = { module = "org.apache.commons:commons-lang3", version = "3.17.0" }
apache_commons_math3 = { module = "org.apache.commons:commons-math3", version = "3.6.1"}

androidx_activity                       = { module = "androidx.activity:activity", version                           = "1.9.1" }
androidx_activity_ktx                   = { module = "androidx.activity:activity-ktx", version                       = "1.9.1" }
androidx_annotation                     = { module = "androidx.annotation:annotation", version                       = "1.8.2" }
androidx_appcompat                      = { module = "androidx.appcompat:appcompat", version                         = "1.7.0" }
androidx_appcompat_resources            = { module = "androidx.appcompat:appcompat-resources", version               = "1.7.0" }
androidx_asynclayoutinflater            = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version     = "1.0.0" }
androidx_cardview                       = { module = "androidx.cardview:cardview", version                           = "1.0.0" }
androidx_collection                     = { module = "androidx.collection:collection", version                       = "1.4.3" }
androidx_constraintlayout               = { module = "androidx.constraintlayout:constraintlayout", version           = "2.1.4" }
androidx_constraintlayout_core          = { module = "androidx.constraintlayout:constraintlayout-core", version      = "1.0.4" }
androidx_constraintlayout_solver        = { module = "androidx.constraintlayout:constraintlayout-solver", version    = "2.0.4" }
androidx_coordinatorlayout              = { module = "androidx.coordinatorlayout:coordinatorlayout", version         = "1.2.0" }
androidx_core                           = { module = "androidx.core:core", version                                   = "1.13.1" }
androidx_core_common                    = { module = "androidx.arch.core:core-common", version                       = "2.2.0" }
androidx_core_ktx                       = { module = "androidx.core:core-ktx", version                               = "1.13.1" }
androidx_core_runtime                   = { module = "androidx.arch.core:core-runtime", version                      = "2.2.0" }
androidx_core_splashscreen              = { module = "androidx.core:core-splashscreen", version                      = "1.1.0-rc01" }
androidx_cursoradapter                  = { module = "androidx.cursoradapter:cursoradapter", version                 = "1.0.0" }
androidx_customview                     = { module = "androidx.customview:customview", version                       = "1.1.0" }
androidx_customview_poolingcontainer    = { module = "androidx.customview:customview-poolingcontainer", version      = "1.0.0" }
androidx_datastore_android              = { module = "androidx.datastore:datastore-android", version                 = "1.1.1" }
androidx_datastore_core                 = { module = "androidx.datastore:datastore-core", version                    = "1.1.1" }
androidx_datastore_core_android         = { module = "androidx.datastore:datastore-core-android", version            = "1.1.1" }
androidx_datastore_core_okio            = { module = "androidx.datastore:datastore-core-okio", version               = "1.1.1" }
androidx_datastore_preferences          = { module = "androidx.datastore:datastore-preferences", version             = "1.1.1" }
androidx_datastore_preferences_core     = { module = "androidx.datastore:datastore-preferences-core", version        = "1.1.1" }
androidx_documentfile                   = { module = "androidx.documentfile:documentfile", version                   = "1.0.1" }
androidx_drawerlayout                   = { module = "androidx.drawerlayout:drawerlayout", version                   = "1.2.0" }
androidx_dynamicanimation               = { module = "androidx.dynamicanimation:dynamicanimation", version           = "1.1.0-alpha03" }
androidx_emoji2                         = { module = "androidx.emoji2:emoji2", version                               = "1.4.0" }
androidx_emoji2_views                   = { module = "androidx.emoji2:emoji2-views", version                         = "1.4.0" }
androidx_emoji2_views_helper            = { module = "androidx.emoji2:emoji2-views-helper", version                  = "1.4.0" }
androidx_fragment                       = { module = "androidx.fragment:fragment", version                           = "1.8.2" }
androidx_fragment_ktx                   = { module = "androidx.fragment:fragment-ktx", version                       = "1.8.2" }
androidx_fragment_testing               = { module = "androidx.fragment:fragment-testing", version                   = "1.8.2" }
androidx_interpolator                   = { module = "androidx.interpolator:interpolator", version                   = "1.0.0" }
androidx_legacy_preference_v14          = { module = "androidx.legacy:legacy-preference-v14", version                = "1.0.0" }
androidx_legacy_support_core_ui         = { module = "androidx.legacy:legacy-support-core-ui", version               = "1.0.0" }
androidx_legacy_support_core_utils      = { module = "androidx.legacy:legacy-support-core-utils", version            = "1.0.0" }
androidx_legacy_support_v4              = { module = "androidx.legacy:legacy-support-v4", version                    = "1.0.0" }
androidx_lifecycle_common               = { module = "androidx.lifecycle:lifecycle-common", version                  = "2.8.4" }
androidx_lifecycle_extensions           = { module = "androidx.lifecycle:lifecycle-extensions", version              = "2.2.0" }
androidx_lifecycle_livedata             = { module = "androidx.lifecycle:lifecycle-livedata", version                = "2.8.4" }
androidx_lifecycle_livedata_core        = { module = "androidx.lifecycle:lifecycle-livedata-core", version           = "2.8.4" }
androidx_lifecycle_livedata_core_ktx    = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version       = "2.8.4" }
androidx_lifecycle_livedata_ktx         = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version            = "2.8.4" }
androidx_lifecycle_process              = { module = "androidx.lifecycle:lifecycle-process", version                 = "2.8.4" }
androidx_lifecycle_runtime              = { module = "androidx.lifecycle:lifecycle-runtime", version                 = "2.8.4" }
androidx_lifecycle_viewmodel            = { module = "androidx.lifecycle:lifecycle-viewmodel", version               = "2.8.4" }
androidx_lifecycle_viewmodel_ktx        = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version           = "2.8.4" }
androidx_lifecycle_viewmodel_savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version    = "2.8.4" }
androidx_loader                         = { module = "androidx.loader:loader", version                               = "1.1.0" }
androidx_localbroadcastmanager          = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version = "1.1.0" }
androidx_media                          = { module = "androidx.media:media", version                                 = "1.7.0" }
androidx_multidex                       = { module = "androidx.multidex:multidex", version                           = "2.0.1" }
androidx_navigation_fragment            = { module = "androidx.navigation:navigation-fragment-ktx", version          = "2.7.7" }
androidx_navigation_ui                  = { module = "androidx.navigation:navigation-ui-ktx", version                = "2.7.7" }
androidx_paging_common                  = { module = "androidx.paging:paging-common", version                        = "3.3.2" }
androidx_paging_common_ktx              = { module = "androidx.paging:paging-common-ktx", version                    = "3.3.2" }
androidx_paging_runtime                 = { module = "androidx.paging:paging-runtime", version                       = "3.3.2" }
androidx_paging_runtime_ktx             = { module = "androidx.paging:paging-runtime-ktx", version                   = "3.3.2" }
androidx_preference                     = { module = "androidx.preference:preference", version                       = "1.2.1" }
androidx_preference_ktx                 = { module = "androidx.preference:preference-ktx", version                   = "1.2.1" }
androidx_print                          = { module = "androidx.print:print", version                                 = "1.0.0" }
androidx_recyclerview                   = { module = "androidx.recyclerview:recyclerview", version                   = "1.3.2" }
androidx_room_common                    = { module = "androidx.room:room-common", version                            = "2.6.1" }
androidx_room_coroutines                = { module = "androidx.room:room-coroutines", version                        = "2.1.0-alpha04" }
androidx_room_ktx                       = { module = "androidx.room:room-ktx", version                               = "2.6.1" }
androidx_room_runtime                   = { module = "androidx.room:room-runtime", version                           = "2.6.1" }
androidx_savedstate                     = { module = "androidx.savedstate:savedstate", version                       = "1.2.1" }
androidx_slidingpanelayout              = { module = "androidx.slidingpanelayout:slidingpanelayout", version         = "1.2.0" }
androidx_sqlite                         = { module = "androidx.sqlite:sqlite", version                               = "2.4.0" }
androidx_sqlite_framework               = { module = "androidx.sqlite:sqlite-framework", version                     = "2.4.0" }
androidx_startup_runtime                = { module = "androidx.startup:startup-runtime", version                     = "1.1.1" }
androidx_swiperefreshlayout             = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version       = "1.1.0" }
androidx_test_espresso                  = { module = "androidx.test.espresso:espresso-core", version                 = "3.6.1" }
androidx_test_ext_junit                 = { module = "androidx.test.ext:junit", version                              = "1.2.1" }
androidx_test_monitor                   = { module = "androidx.test:monitor", version                                = "1.7.2" }
androidx_test_orchestrator              = { module = "androidx.test:orchestrator", version                           = "1.5.0" }
androidx_test_rules                     = { module = "androidx.test:rules", version                                  = "1.6.1" }
androidx_test_runner                    = { module = "androidx.test:runner", version                                 = "1.6.2" }
androidx_test_core                      = { module = "androidx.test:core", version                                   = "1.6.1" }
androidx_tracing                        = { module = "androidx.tracing:tracing", version                             = "1.2.0" }
androidx_transition                     = { module = "androidx.transition:transition", version                       = "1.5.1" }
androidx_transition_ktx                 = { module = "androidx.transition:transition-ktx", version                   = "1.5.1" }
androidx_vectordrawable                 = { module = "androidx.vectordrawable:vectordrawable", version               = "1.2.0" }
androidx_vectordrawable_animated        = { module = "androidx.vectordrawable:vectordrawable-animated", version      = "1.2.0" }
androidx_versionedparcelable            = { module = "androidx.versionedparcelable:versionedparcelable", version     = "1.2.0" }
androidx_viewbinding                    = { module = "androidx.databinding:viewbinding", version                     = "8.6.0" }
androidx_viewpager                      = { module = "androidx.viewpager:viewpager", version                         = "1.0.0" }
androidx_viewpager2                     = { module = "androidx.viewpager2:viewpager2", version                       = "1.1.0" }
androidx_webkit                         = { module = "androidx.webkit:webkit", version                               = "1.11.0" }
androidx_work_runtime                   = { module = "androidx.work:work-runtime", version                           = "2.9.1" }
