dependencies {
  testImplementation(project(":com.io7m.exfilac.content_tree.api"))
  testImplementation(project(":com.io7m.exfilac.core"))
  testImplementation(project(":com.io7m.exfilac.s3_uploader.amazon"))
  testImplementation(project(":com.io7m.exfilac.s3_uploader.api"))
  testImplementation(project(":com.io7m.exfilac.service.api"))

  testImplementation(libs.junit.jupiter.api)
  testImplementation(libs.junit.jupiter.engine)
  testImplementation(libs.junit.platform.commons)
  testImplementation(libs.junit.platform.engine)
  testImplementation(libs.junit.platform.launcher)
  testImplementation(libs.opentest4j)
  testImplementation(libs.logback.core)
  testImplementation(libs.logback.classic)
  testImplementation(libs.jqwik.api)
  testImplementation(libs.jqwik.engine)

  testImplementation(libs.io7m.anethum.api)
  testImplementation(libs.io7m.blackthorne.core)
  testImplementation(libs.io7m.blackthorne.jxe)
  testImplementation(libs.io7m.darco.api)
  testImplementation(libs.io7m.darco.sqlite)
  testImplementation(libs.io7m.ervilla.api)
  testImplementation(libs.io7m.ervilla.ext)
  testImplementation(libs.io7m.ervilla.native.exec)
  testImplementation(libs.io7m.jade.api)
  testImplementation(libs.io7m.jade.spi)
  testImplementation(libs.io7m.jade.vanilla)
  testImplementation(libs.io7m.jaffirm.core)
  testImplementation(libs.io7m.jattribute.core)
  testImplementation(libs.io7m.jdeferthrow.core)
  testImplementation(libs.io7m.jlexing.core)
  testImplementation(libs.io7m.jmulticlose.core)
  testImplementation(libs.io7m.junreachable.core)
  testImplementation(libs.io7m.jxe.core)
  testImplementation(libs.io7m.lanark.core)
  testImplementation(libs.io7m.peixoto.sdk)
  testImplementation(libs.io7m.seltzer.api)
  testImplementation(libs.io7m.taskrecorder.core)
  testImplementation(libs.io7m.trasco.api)
  testImplementation(libs.io7m.trasco.vanilla)
  testImplementation(libs.io7m.trasco.xml.schemas)

  testImplementation(libs.apache.commons.io)
  testImplementation(libs.apache.commons.lang3)
  testImplementation(libs.apache.commons.math3)
  testImplementation(libs.kotlin.stdlib)
  testImplementation(libs.logback.android)
  testImplementation(libs.opentelemetry.api)
  testImplementation(libs.opentelemetry.context)
  testImplementation(libs.slf4j)
  testImplementation(libs.stax)
  testImplementation(libs.stax.api)
  testImplementation(libs.stax.api)
  testImplementation(libs.xerces)
  testImplementation(libs.xerial.sqlite)
}

afterEvaluate {
  tasks.matching { task -> task.name.contains("UnitTest") }
    .forEach { task -> task.enabled = true }
}
