fun getGitHash(): String {
  val proc = ProcessBuilder("git", "rev-parse", "--short", "HEAD")
    .redirectOutput(ProcessBuilder.Redirect.PIPE)
    .redirectError(ProcessBuilder.Redirect.PIPE)
    .start()

  proc.waitFor(10L, TimeUnit.SECONDS)
  return proc.inputStream.bufferedReader().readText().trim()
}

android {
  buildFeatures {
    buildConfig = true
  }

  defaultConfig {
    buildConfigField("String", "EXFILAC_GIT_COMMIT", "\"${getGitHash()}\"")
    buildConfigField("String", "EXFILAC_VERSION", "\"${rootProject.ext["VERSION_NAME"]}\"")
  }
}

dependencies {
  implementation(project(":com.io7m.exfilac.clock.api"))
  implementation(project(":com.io7m.exfilac.content_tree.api"))
  implementation(project(":com.io7m.exfilac.content_tree.device"))
  implementation(project(":com.io7m.exfilac.core"))
  implementation(project(":com.io7m.exfilac.s3_uploader.amazon"))
  implementation(project(":com.io7m.exfilac.s3_uploader.api"))
  implementation(project(":com.io7m.exfilac.service.api"))

  implementation(libs.io7m.anethum.api)
  implementation(libs.io7m.blackthorne.core)
  implementation(libs.io7m.blackthorne.jxe)
  implementation(libs.io7m.darco.api)
  implementation(libs.io7m.darco.sqlite)
  implementation(libs.io7m.jaffirm.core)
  implementation(libs.io7m.jattribute.core)
  implementation(libs.io7m.jlexing.core)
  implementation(libs.io7m.jmulticlose.core)
  implementation(libs.io7m.junreachable.core)
  implementation(libs.io7m.jxe.core)
  implementation(libs.io7m.lanark.core)
  implementation(libs.io7m.peixoto.sdk)
  implementation(libs.io7m.seltzer.api)
  implementation(libs.io7m.taskrecorder.core)
  implementation(libs.io7m.trasco.api)
  implementation(libs.io7m.trasco.vanilla)
  implementation(libs.io7m.trasco.xml.schemas)

  implementation(libs.apache.commons.io)
  implementation(libs.kotlin.stdlib)
  implementation(libs.logback.android)
  implementation(libs.opentelemetry.api)
  implementation(libs.opentelemetry.context)
  implementation(libs.slf4j)
  implementation(libs.stax)
  implementation(libs.stax.api)
  implementation(libs.xerces)
  implementation(libs.xerial.sqlite)

  // QR code reader.
  implementation(libs.zxing.embedded)
  implementation(libs.zxing.core)

  // Theme
  implementation(libs.google.material)

  implementation(libs.androidx.activity)
  implementation(libs.androidx.activity.ktx)
  implementation(libs.androidx.annotation)
  implementation(libs.androidx.appcompat)
  implementation(libs.androidx.appcompat.resources)
  implementation(libs.androidx.cardview)
  implementation(libs.androidx.collection)
  implementation(libs.androidx.constraintlayout)
  implementation(libs.androidx.constraintlayout.core)
  implementation(libs.androidx.constraintlayout.solver)
  implementation(libs.androidx.coordinatorlayout)
  implementation(libs.androidx.core)
  implementation(libs.androidx.core.common)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.core.runtime)
  implementation(libs.androidx.core.splashscreen)
  implementation(libs.androidx.cursoradapter)
  implementation(libs.androidx.customview)
  implementation(libs.androidx.customview.poolingcontainer)
  implementation(libs.androidx.documentfile)
  implementation(libs.androidx.drawerlayout)
  implementation(libs.androidx.emoji2)
  implementation(libs.androidx.emoji2.views)
  implementation(libs.androidx.emoji2.views.helper)
  implementation(libs.androidx.fragment)
  implementation(libs.androidx.fragment.ktx)
  implementation(libs.androidx.interpolator)
  implementation(libs.androidx.lifecycle.common)
  implementation(libs.androidx.lifecycle.extensions)
  implementation(libs.androidx.lifecycle.livedata)
  implementation(libs.androidx.lifecycle.livedata.core)
  implementation(libs.androidx.lifecycle.livedata.core.ktx)
  implementation(libs.androidx.lifecycle.livedata.ktx)
  implementation(libs.androidx.lifecycle.process)
  implementation(libs.androidx.lifecycle.runtime)
  implementation(libs.androidx.lifecycle.viewmodel)
  implementation(libs.androidx.lifecycle.viewmodel.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.savedstate)
  implementation(libs.androidx.loader)
  implementation(libs.androidx.multidex)
  implementation(libs.androidx.paging.common)
  implementation(libs.androidx.paging.common.ktx)
  implementation(libs.androidx.paging.runtime)
  implementation(libs.androidx.paging.runtime.ktx)
  implementation(libs.androidx.preference)
  implementation(libs.androidx.preference.ktx)
  implementation(libs.androidx.recyclerview)
  implementation(libs.androidx.savedstate)
  implementation(libs.androidx.startup.runtime)
  implementation(libs.androidx.tracing)
  implementation(libs.androidx.vectordrawable)
  implementation(libs.androidx.vectordrawable.animated)
  implementation(libs.androidx.viewpager)
  implementation(libs.androidx.viewpager2)

  implementation(libs.kotlinx.coroutines)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core.jvm)
}
