name: main.windows.temurin.lts

on:
  push:
    branches: [ develop, master, feature/*, release/* ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build
        run: java make/Make.java
